# Generated by Django 5.1.8 on 2025-07-24 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0007_savedjobs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='savedjobs',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
