# Generated by Django 5.1.8 on 2025-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0009_linkedinprofile_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
