# Generated by Django 5.1.8 on 2025-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0010_job_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
