# Generated by Django 5.1.8 on 2025-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0011_remove_job_email_searchquery_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_limit', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
